# site properties and page defaults
title: The Horlbeck Lab
subtitle: 
description: We study **Chromatinopathies**, a large class of genetic disorders in which disruption in chromatin modifying machinery leads to developmental delay and intellectual disability. Using high-throughput genetic screening and epigenomic readouts, we seek to understand how chromatin regulation shapes cell fate decisions and identify paths to treatment for these disorders.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  orcid: 0000-0002-3875-871X
  google-scholar: uJyzT6EAAAAJ
  github: horlbeck-lab
  twitter: horlbeck-lab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
